In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [69]:
df = pd.read_csv("../data/student_performance_dataset.csv")

pd.options.display.max_columns = 500

df

,student_id,age,gender,city_type,study_hours_per_day,deep_work_sessions,assignment_completion_rate,attendance_percentage,social_media_hours,doomscrolling_before_sleep,notification_distractions,ai_tool_usage_hours,gaming_hours,stress_level,motivation_level,focus_score,procrastination_index,mental_state,sleep_hours,caffeine_intake,physical_activity_hours,internet_quality,family_support,financial_stress,learning_style,career_goal,productivity_after_midnight,revision_efficiency,burnout_risk,consistency_score,final_exam_score,performance_category
0,0,21,Female,Semi-Urban,3.2,7,100,70,3.8,0,107,0.6,1.8,8,5,4.0,8,Balanced,5.8,4,0.6,1,10,6,Audio,Engineering,9,1,10,3,32,Low
1,1,19,Female,Semi-Urban,3.9,2,46,70,2.6,1,93,1.5,1.1,4,7,8.0,3,Burnout,6.1,5,0.0,4,2,6,Practical,Business,6,10,4,6,59,Medium
2,2,16,Female,Urban,4.3,7,54,57,4.3,1,82,0.5,0.0,2,5,8.0,10,Burnout,6.6,4,1.3,9,1,9,Visual,Engineering,7,9,8,1,34,Low
3,3,19,Male,Semi-Urban,5.3,1,78,90,1.7,0,27,1.4,3.8,8,6,3.0,1,Burnout,8.0,2,1.3,1,5,10,Reading,Medical,7,7,9,10,60,Medium
4,4,17,Female,Urban,4.1,3,100,81,2.6,0,8,1.3,2.5,4,7,3.0,6,Focused,6.9,5,1.7,9,5,6,Visual,Medical,4,10,7,9,77,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,22,Female,Rural,2.4,0,40,83,1.0,0,71,2.7,2.0,10,2,1.0,8,Balanced,7.4,4,1.2,5,10,2,Practical,Arts,9,10,7,9,45,Low
2996,2996,19,Female,Urban,5.2,7,94,100,1.4,0,114,3.2,3.8,2,9,8.0,4,Burnout,8.0,2,0.2,3,1,10,Visual,Medical,5,3,7,9,100,High
2997,2997,23,Female,Rural,5.9,2,41,86,5.4,1,88,0.0,2.9,1,6,7.0,9,Balanced,5.2,2,0.5,5,7,10,Practical,Engineering,6,8,10,10,50,Medium
2998,2998,17,Male,Urban,3.9,1,92,96,2.8,1,94,1.8,2.8,6,10,7.0,2,Focused,9.1,0,1.1,7,3,10,Practical,Medical,4,7,1,4,76,High
2999,2999,16,Female,Semi-Urban,5.8,0,84,100,3.8,1,108,1.9,1.9,4,6,7.0,1,Distracted,6.6,1,1.6,9,1,3,Audio,Arts,8,9,2,10,100,High

In [70]:
df = df.set_index("student_id")
df.head()

,age,gender,city_type,study_hours_per_day,deep_work_sessions,assignment_completion_rate,attendance_percentage,social_media_hours,doomscrolling_before_sleep,notification_distractions,ai_tool_usage_hours,gaming_hours,stress_level,motivation_level,focus_score,procrastination_index,mental_state,sleep_hours,caffeine_intake,physical_activity_hours,internet_quality,family_support,financial_stress,learning_style,career_goal,productivity_after_midnight,revision_efficiency,burnout_risk,consistency_score,final_exam_score,performance_category
student_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,21,Female,Semi-Urban,3.2,7,100,70,3.8,0,107,0.6,1.8,8,5,4.0,8,Balanced,5.8,4,0.6,1,10,6,Audio,Engineering,9,1,10,3,32,Low
1,19,Female,Semi-Urban,3.9,2,46,70,2.6,1,93,1.5,1.1,4,7,8.0,3,Burnout,6.1,5,0.0,4,2,6,Practical,Business,6,10,4,6,59,Medium
2,16,Female,Urban,4.3,7,54,57,4.3,1,82,0.5,0.0,2,5,8.0,10,Burnout,6.6,4,1.3,9,1,9,Visual,Engineering,7,9,8,1,34,Low
3,19,Male,Semi-Urban,5.3,1,78,90,1.7,0,27,1.4,3.8,8,6,3.0,1,Burnout,8.0,2,1.3,1,5,10,Reading,Medical,7,7,9,10,60,Medium
4,17,Female,Urban,4.1,3,100,81,2.6,0,8,1.3,2.5,4,7,3.0,6,Focused,6.9,5,1.7,9,5,6,Visual,Medical,4,10,7,9,77,High