# Titanic Survival Prediction Dataset

In [1]:
# Import import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 1. Explore data

1. 11 attributes in this dataset, for now we can say `PassengerId` should not be used (can be used as index).
2. `Survived` attribute is the predicted value in this dataset, when setting X drop this attribute (already set to binary!).
3. `Pclass` (categorical attribute even though it is numercial) refer to the status of the person.\
4. `Name` is irrelevant for prediciton.
5. `Age` is missing for some samples we may need to refill these attr using mean, most_frequant, etc..
6. Ticket should be irrelvant.
7. The ticket price paid in british pound.
8. `Cabin` CONFUSED.
9. `Embarked` The port where the passenger boarded the ship.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

### 1.1 People's age (Are there any invalid ages?)

In [8]:
invalid_ages = df[df["Age"] < 0].value_counts()
invalid_ages

Series([], Name: count, dtype: int64)

### Cabin's Options (How many options are there?)


There are lots of values/options for the cabin attr, but also we have many missing data samples, so this attr should be dropped.

One can argue that the cabin number is relevent because it might be close or far from the colision but we can't analyze this type of problem statement for this datset.

In [12]:
df["Cabin"].value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F33            3
E101           3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [13]:
df = df.drop("Cabin", axis=1)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

### Name attr

This attr should be dropped. It can't help in anyway.

In [14]:
df = df.drop("Name", axis=1)
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,female,35.0,1,0,113803,53.1000,S
4,5,0,3,male,35.0,0,0,373450,8.0500,S

### Ticket

The same as `Name` attr how could this be relevant??

In [15]:
df = df.drop("Ticket", axis=1)
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [16]:
df = df.set_index("PassengerId")

In [17]:
df.head()

             Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
PassengerId
1                   0       3    male  22.0      1      0   7.2500        S
2                   1       1  female  38.0      1      0  71.2833        C
3                   1       3  female  26.0      0      0   7.9250        S
4                   1       1  female  35.0      1      0  53.1000        S
5                   0       3    male  35.0      0      0   8.0500        S

### Sex attr

this attr should be changed into binary attr

In [19]:
df['Sex'] = df["Sex"].apply(lambda x: 1 if x == "male" else 0)
df.head()

             Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
PassengerId
1                   0       3    1  22.0      1      0   7.2500        S
2                   1       1    0  38.0      1      0  71.2833        C
3                   1       3    0  26.0      0      0   7.9250        S
4                   1       1    0  35.0      1      0  53.1000        S
5                   0       3    1  35.0      0      0   8.0500        S

### Age attr

A sklearn imputer will be used to fill up these missing values

1. Check if these missing values are set to `nan`.
2. then use sklearn to place the mean value in place of `nan`.

In [26]:
df["Age"].isna().sum()

np.int64(177)

In [27]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=np.nan, strategy="mean")
df[["Age"]] = imp.fit_transform(df[["Age"]])

In [28]:
df["Age"].isna().sum()

np.int64(0)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    str
dtypes: float64(2), int64(5), str(1)
memory usage: 55.8 KB

### Embarked

1. Use `SimpleImputer` to fill missing values.
2. Check for missing values.

In [30]:
imp_embarked = SimpleImputer(strategy="most_frequent")

df[["Embarked"]] = imp_embarked.fit_transform(df[["Embarked"]])

In [33]:
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    int64
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Embarked_Q  891 non-null    bool
 8   Embarked_S  891 non-null    bool
dtypes: bool(2), float64(2), int64(5)
memory usage: 50.6 KB

In [36]:
df = df.map(lambda x: 1 if x is True else 0 if x is False else x)

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    int64
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Embarked_Q  891 non-null    int64
 8   Embarked_S  891 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 62.8 KB

In [38]:
df = pd.get_dummies(df, columns=["Pclass"], drop_first=True)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Sex         891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Embarked_Q  891 non-null    int64
 7   Embarked_S  891 non-null    int64
 8   Pclass_2    891 non-null    bool
 9   Pclass_3    891 non-null    bool
dtypes: bool(2), float64(2), int64(6)
memory usage: 57.6 KB

In [40]:
df = df.map(lambda x: 1 if x is True else 0 if x is False else x)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Sex         891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Embarked_Q  891 non-null    int64
 7   Embarked_S  891 non-null    int64
 8   Pclass_2    891 non-null    int64
 9   Pclass_3    891 non-null    int64
dtypes: float64(2), int64(8)
memory usage: 69.7 KB